hour=float(input("enter the hours"))
rate=float(input("enter the rate"))
print("pay",rate*hour)

In [14]:
num=int(input("enter the number"))
if num==5:
    print(num," is equal to 5")
if num<6:
    print(num," is less then 6")
if num>4:
    print(num," is grater then 4")
if num<=5:
    print(num," is less then or equal to 5")
if num>=5:
    print(num," is grater then or equalto 5")
if num!=4:
    print(num," is not equal to 5")
    
    

enter the number5
5  is equal to 5
5  is less then 6
5  is grater then 4
5  is less then or equal to 5
5  is grater then or equalto 5
5  is not equal to 5


In [9]:
num=int(input("enter the num"))
if num<2:
    print("below 2")
elif num>=2:
    print("2 or more")
else:
    print("sumthing else")

enter the num2
2 or more


In [23]:
astr="hello bob"
try:
    istr=int(astr)
except:
    istr=-1    
print('frist',istr)
astr='123'
try:
    istr=int(astr)
except:
    istr=-1
print('second',istr)

frist -1
second 123


In [24]:
astr='bob'
try:
    print('hello')
    istr=int(astr)
    print('there')
except:
    istr=-1
print('done',istr)

hello
done -1


In [38]:
astr=input("enter the number")
try:
    istr=int(astr)
except:
    istr=-1
if istr>0:
    print("good job")
else:
    print("kindly enter the number")

enter the number7
good job


In [33]:
hour=float(input("enter the hours"))
rate=float(input("enter the rate"))
if hour>40:
    extime=hour-40
    pay=40*rate+extime*(rate*1.5)
else:
    pay=hour*rate
print("pay is",pay)

enter the hours45
enter the rate10
pay is 475.0


In [41]:
while True:
    line=input('<')
    if line=='done':
        break
    print(line)
print('done!')

<done
done!


In [47]:
while True:
    line=input('<')
    if line[0]=='#':
        continue
    if line=='done':
        break
    else:
        break
    print(line)
print('done!')

<#
<#
<#
<done
done
done!


In [48]:
friends=['ajith','chandan','shaheel']
for i in friends:
    print(i)

ajith
chandan
shaheel


In [50]:
friends=['ajith','chandan','shaheel']
print('before')
for i in friends:
    print(i)
print('after')

before
ajith
chandan
shaheel
after


In [51]:
large=0;
lis=[10,20,49,29,102,2839,13913193]
for i in lis:
    if i>large:
        large=i
print(large)

13913193


In [54]:
large=0
num=29
lis=[10,20,49,29,102,2839,13913193]
if num in lis:
    print("true")
else:
    print("false")

true


In [105]:
num=int(input("enter the number"))
if num is 5:
    print(num," is equal to 5")
if num is not 5:
    print(num," is not equal to 5")

enter the number5
5  is equal to 5


In [95]:
sales={
    'price':3.14,
    'no_items':10,
    'person':"abc"
}
sales_statement='{} brought {} items at price {} total {} '
print(sales_statement.format(sales['person'],
                            sales['no_items'],
                            sales['price'],
                            int(sales['price']*sales['no_items'])))

abc brought 10 items at price 3.14 total 31 


In [85]:
import time as t
import datetime as d
t.time()
ac=d.timedelta(days=100)
print(d.date.today()-ac)


2019-05-06


In [104]:
class Person:
    inst="manipal school of info science"
    def set_name(self,new_name):
        self.name=new_name
    #def set_loc(self,new_loc):
     #   self.loc=new_loc
person=Person()
person.set_name("abc")
#person.set_loc("shimoga")
person.loc='shimoga'
print('{} lives in {} and studies in {}'.format(person.name,person.loc,person.inst))

abc lives in shimoga and studies in manipal school of info science


In [129]:
abc=[21,32,43,65,63,87698,52,67]
cdf=[12,34,13,43,35,42,242,23433]
low=map(min,abc,cdf)
abc=list(low)
abc.sort()
for i in abc:
    print(i)

12
13
32
35
42
43
52
67


In [118]:
my_fun=lambda a,b,c: a+b+c
print(my_fun(5,3,5))

13


In [116]:
def split_title_and_name(person):
     print(person.split()[0]+ ' '+person.split()[-1])
people=['Dr abc','dr new','dr eqe']
for abc in people:
    split_title_and_name(abc)

Dr abc
dr new
dr eqe


In [31]:
my_fun=lambda abc:abc.split()[0]+ ' '+abc.split()[-1]
people=['Dr abc','dr new','dr eqe']
for abc in people:
    print(my_fun(abc))

Dr abc
dr new
dr eqe


In [32]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
for i in np.nditer(a):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-32-0ecfef589239>, line 5)

In [10]:
def calsquare(n):
    return n*n
lis=1,2,3
res=map(calsquare,lis)
for i in res:
    print(i)


In [23]:
num1=[1,2,3]
num2=[1,2,3]
my_fun=map(lambda a,b: a+b,num1,num2)
print(list(my_fun))

[2, 4, 6]


In [28]:
person=['Dr abc','dr new','dr eqe']
def split_title_and_name(person):
    title=person.split()[0]
    lastname=person.split()[-1]
    return '{} {}'.format(title,lastname)
list(map(split_title_and_name,person))

['Dr abc', 'dr new', 'dr eqe']

In [33]:
lis=[num for num in range(0,20) if num%2==0]
lis

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [40]:
dic=[num*num2 for num in range(1,11) for num2 in range(1,11) ]
print(dic)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [41]:
import numpy as np
arr=np.arange(10)
print(arr)
b=arr.reshape(2,5)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [44]:
import numpy as np
lis=[1,2,3,4,5,6]
arr=np.array(lis)
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
arr=np.linspace(1,7,4)
print(arr.reshape(2,2))



[[ 1.  3.]
 [ 5.  7.]]


In [62]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [76]:
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
arr=np.arange(16)
b=arr.reshape(4,4)
print(b)
print()
print(np.diag(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[ 0  5 10 15]


In [131]:
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [86]:
p=np.ones((3,3),int)
np.vstack((p,p*5))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [130]:
np.hstack((p,p*4))


array([[1, 1, 1, 4, 4, 4],
       [1, 1, 1, 4, 4, 4],
       [1, 1, 1, 4, 4, 4]])

In [132]:
r=np.arange(100)
r.resize((10,10))
print(r)
print()
print(np.diag(r),'\n')
print(np.diag(r,1),'\n')
print(np.diag(r,-1),'\n')
print(r[:3,:3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[ 0 11 22 33 44 55 66 77 88 99] 

[ 1 12 23 34 45 56 67 78 89] 

[10 21 32 43 54 65 76 87 98] 

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
